version: 2

models:
    - name: eia_average
      description: "EIA data averaged across time zones"
      columns:
        - name: period
          description: "Date field at the day level"
          data_tests:
            - not_null
        - name: avg_mwh
          description: "Megawatt-hours aggregated to the subregion level, averaged across timezones"
          data_tests:
            - not_null
            - not_zero

    - name: eia_eastern
      description: "EIA data filtered to Eastern time zone"