version: 2

models:
    - name: fact_demand
      description: "Fact table for demand values"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: ba_key
            description: "The foreign key for dim_balancing_authority"
            data_tests:
            - relationships:
                arguments:
                  to: ref('dim_balancing_authority')
                  field: ba_key
          - name: subregion_key
            description: "The foreign key for dim_subregion"
            data_tests:
            - relationships:
                arguments:
                  to: ref('dim_subregion')
                  field: subregion_key
          - name: date_key
            description: "The foreign key for dim_date"
            data_tests:
            - relationships:
                arguments:
                  to: ref('dim_date')
                  field: date_key

    - name: dim_balancing_authority
      description: "Dimension table for balancing authorities"
      columns:
          - name: ba_key
            description: "Primary key"
            tests:
                - unique
                - not_null

    - name: dim_subregion
      description: "Dimension table for subregions within balancing authorities"
      columns:
          - name: subregion_key
            description: "Primary key"
            tests:
                - unique
                - not_null

    - name: dim_date
      description: "Dimension table for dates"
      columns:
          - name: date_key
            description: "Primary key"
            tests:
                - unique
                - not_null
